      PROGRAM MAIN
 
      INTEGER DATE
      REAL SRAD, TMAX, TMIN, RAIN, PAR
      OPEN (10, FILE="test_file.INP")
      OPEN (20, FILE="out_file", STATUS="REPLACE")
      READ (10,10) DATE, SRAD, TMAX, TMIN, RAIN, PAR
      WRITE (20,10) DATE, SRAD, TMAX, TMIN, RAIN, PAR
 10   FORMAT (I5,2X,F4.1,2X,F4.1,2X,F4.1,F6.1,14X,F4.1)
      STOP
      END PROGRAM MAIN
