version: '3'

services:
  delphi:
    image: delphi:latest
    container_name: delphi
    build: .
    volumes:
        - ./data:/delphi/data
    working_dir: /delphi
    ports:
      - "5000:8123"
    entrypoint: ./build/delphi_rest_api --host 0.0.0.0
