language: cpp
dist: trusty
sudo: require

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - clang++-5.0
            - valgrind
            - gcc-8-base
            - libc6
            - libgcc1
      env:
        - COMPILER=clang++-5.0
        - USE_LIBCXX=1
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - clang++-6.0
            - valgrind
            - gcc-8-base
            - libc6
            - libgcc1
      env:
        - COMPILER=clang++-6.0
        - USE_LIBCXX=1
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - valgrind
      env:
        - COMPILER=g++-7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - valgrind
      env:
        - COMPILER=g++-8

script:
  - ${COMPILER} --version
  - CXX="${COMPILER}" scons
  - ./test_all
  - valgrind ./test_all


before_script:
  - if [ -n "${USE_LIBCXX}" ]; then
    bash .install-libcxx-travis.sh;
    fi
  - cd test
  - ./download_catch.sh
