#!/bin/bash

# Author: Joseph Astier

# Check the status of Database tables of interest

printf "Testing Delphi REST API check_data function:\n"

endpoint="/check_data"
login="-u me:ivilab4fun"
url=$(./get_delphi_url)

call="curl $login -s $url$endpoint"

echo $($call)
