#!/bin/bash

# Authors: Joseph Astier, Adarsh Pyarelal

# Set the ROOT environment variable, assuming that the directory structure
# mirrors that of the git repository.
ROOT="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../../../" >/dev/null 2>&1 && pwd)"
export ROOT

# Test if there is a delphi_rest_api process running

printf "Testing Delphi REST API status:\n"

endpoint="/status"
login="-u me:ivilab4fun"
url=$(. $ROOT/tests/wm/scripts/get_delphi_url)

call="curl $login -s $url$endpoint"
echo "Call:"
echo $call

response=$($call)
echo "Response:"
echo $response
