#!/bin/bash

# Author: Joseph Astier

# Return either the local or remote delphi URL.

# uncomment for "Delphi dev" connection on Gauss
# printf "http://ivilab.org/delphi-api"

# uncomment for use on local machine
printf "http://localhost:8123"
