#!/bin/bash

# Author: Joseph Astier
#
# Watch the database from outside of the delphi_rest_api

call="sqlite3 /home/jastier/delphi.db select(data)from(model_status);"

echo "call = $call"

for i in {0..1000}
do
    echo $(date +%T.%3N) $($call)
    sleep 0.1
done

echo "Done"

