#!/bin/bash

# Usage: ./autoTranslate <fortran files>

checkVersion() {
    versionStr=$($1 --version 2>&1)

    if [[ $? -ne 0 ]]; then
        continue
    fi

    IFS=' ' read -r -a versionStr <<< "$versionStr"

    versionStr=${versionStr[${#versionStr[@]}-1]}

    IFS='. ' read -r -a version <<< "$versionStr"

    if [ "${version[0]}" -eq 3 ] && [ "${version[1]}" -ge 6 ]; then
        cmp=1
    else
        cmp=0
    fi
}

findExec() {
    for p in $(compgen -c python); do 
        checkVersion $p

        if [ $cmp -eq 1 ]; then
            export PYTRANSLATE=$p
        fi
    done
}

if [ $# -eq 0 ]; then
    echo "Usage: $0 <fortran files>"
    exit 1
fi

export CLASSPATH="${CLASSPATH}:"$(pwd)/$(dirname ${BASH_SOURCE[0]})"/bin/*"
pyFiles=""

if [ -z "$PYTRANSLATE" ]; then
    findExec
    if [ -z "$PYTRANSLATE" ]; then
        echo 'Could not find python > 3.6'
        exit 1
    fi
fi

# Creating a directory for intermediate files
mkdir -p tmp

for file in "$@"; do
    base=$(basename "$file")
    extension=${base##*.}
    base=${base%.*}
    processedFile=tmp/"$base"_processed."$extension"
    pickleFile=tmp/"$base"_pickle
    astFile=tmp/"$base".xml
    rectifiedAstFile=tmp/rectified_"$base".xml
    ( set -x; $PYTRANSLATE preprocessor.py "$file" "$processedFile") 
    ( set -x; java fortran.ofp.FrontEnd --class fortran.ofp.XMLPrinter --verbosity 0 "$processedFile" > "$astFile")
    ( set -x; $PYTRANSLATE rectify.py "$astFile")

    pyFile=tmp/"$base".py
    outputFileList=tmp/"$base"_outputList.txt
    ( set -x; $PYTRANSLATE translate.py -f "$rectifiedAstFile" -g "$pickleFile" -i "$file")
    ( set -x; $PYTRANSLATE pyTranslate.py -f "$pickleFile" -g "$pyFile" -o "$outputFileList")
    pyFiles+=" $pyFile"
done

( set -x; $PYTRANSLATE genPGM.py -f$pyFiles -p GrFN.json -l lambdas.py -o $outputFileList)
