      SUBROUTINE UPDATE_EST(RAIN, TOTAL_RAIN, YIELD_EST)
        DOUBLE PRECISION RAIN, YIELD_EST, TOTAL_RAIN
        TOTAL_RAIN = TOTAL_RAIN + RAIN
        IF(TOTAL_RAIN .le. 40) THEN
            YIELD_EST = -(TOTAL_RAIN - 40) ** 2 / 16 + 100
        ELSE
            YIELD_EST = -TOTAL_RAIN + 140
        ENDIF
      END SUBROUTINE UPDATE_EST
      PROGRAM CROP_YIELD
      IMPLICIT NONE
      INTEGER DAY
      DOUBLE PRECISION RAIN, YIELD_EST, TOTAL_RAIN
      DOUBLE PRECISION MAX_RAIN, CONSISTENCY, ABSORPTION
      MAX_RAIN = 4.0
      CONSISTENCY = 64.0
      ABSORPTION = 0.6
      YIELD_EST = 0
      TOTAL_RAIN = 0
      DO 20 DAY=1,31
        RAIN = (-(DAY - 16) ** 2 / CONSISTENCY + MAX_RAIN) * ABSORPTION
        CALL UPDATE_EST(RAIN, TOTAL_RAIN, YIELD_EST)
        PRINT *, "Day ", DAY, " Estimate: ", YIELD_EST
   20 ENDDO
      PRINT *, "Crop Yield(%): ", YIELD_EST
      END PROGRAM CROP_YIELD
