openapi: 3.0.0

info:
  title: GrFN Spec
  description: Grounded Function Network (GrFN) Specification
  contact:
    name: Clayton T. Morrison
    email: claytonm@email.arizona.edu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 0.2.2

paths: {}

components:

  schemas:

    system_def:
      title: <system_def>
      description: >
        Specification of a GrFN system consisting of one or
        more GrFN_spec files.
        With imports, the system must represent a DAG.
      required:
        - date_created
        - name
        - components
      properties:
        date_created:
          type: string
          format: date-time
        name:
          type: string
        components:
          type: array
          items:
            $ref: '#/components/schemas/grfn_spec_ref'

    grfn_spec_ref:
      title: <grfn_spec_ref>
      description: >
        Specifies a GrFN_spec file that is part of a GrFN system.
        "imports" (optional) specifies list of any GrFN_spec files
        that need to also be loaded due to dependencies.
      required:
        - name
      properties:
        name:
          $ref: '#/components/schemas/namespace_path_string'
        imports:
          type: array
          items:
            $ref: '#/components/schemas/namespace_path_string'

    grfn_spec:
      title: <grfn_spec>
      description: >
        The top-level structure of the GrFN specification.
      required:
        - date_created
        - source
        - identifiers
        - variables
        - functions
      properties:
        date_created:
          type: string
          format: date-time
          description: >
            Date and time that current GrFN was generated.
        source:
          type: array
          items:
            $ref: '#/components/schemas/source_code_file_path'
        start:
          type: array
          items:
            $ref: '#/components/schemas/function_name'
          description:
            (optional) Top-level entry-points into program
        identifiers:
          type: array
          items:
            $ref: '#/components/schemas/identifier_spec'
        types:
          type: array
          items:
            $ref: '#/components/schemas/type_spec'
        variables:
          type: array
          items:
            $ref: '#/components/schemas/variable_spec'
        functions:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/function_assign_spec'
              - $ref: '#/components/schemas/function_container_spec'

    identifier_spec:
      title: <identifier_spec>
      description: >
        Defines a source code identifier, the context of it's creation
        and use, and associates with it a unique gensym and any
        grounding metadata.
      required:
        - base_name
        - scope
        - namespace
        - source_references
        - gensym
      properties:
        base_name:
          $ref: '#/components/schemas/base_name'
        scope:
          $ref: '#/components/schemas/scope_path'
        namespace:
          $ref: '#/components/schemas/namespace_path'
        source_references:
          type: array
          items:
            $ref: '#/components/schemas/source_code_reference'
        gensym:
          $ref: '#/components/schemas/gensym'
        grounding:
          type: array
          items:
            $ref: '#/components/schemas/grounding_metadata_spec'

    base_name:
      title: <base_name>
      description:
        The identifier name (when available) that was used in the
        original source code.
      type: string

    scope_path:
      title: <scope_path>
      description: >
        Array of names identifying a program scope.
      type: array
      items:
        type: string

    scope_path_string:
      title: <scope_path_string>
      description: >
        String representation of a `<scope_path>`.
        String names that make up components of the path are
        expressed in order, separated by periods.
      example:
        '"foo.loop$1.loop$2"'
      type: string

    namespace_path:
      title: <namespace_path>
      description: >
        Array of names representing a namespace.
      type: array
      items:
        type: string

    namespace_path_string:
      title: <namespace_path_string>
      description: >
        Single string representation of a `<namespace_path>`.
        String names that make up components of the path are
        expressed in order, separated by periods.
      example:
        '"foo.bar.baz"'
      type: string

    gensym:
      title: <gensym>
      description: >
        String representation of a unique gensym.
        Used as identifiers in lambdas and other source code
        generated from GrFN.
      type: string

    grounding_metadata_spec:
      title: <grounding_metadata_spec>
      description: >
        Text Reading currently extracts three types of information
        that can be associated with identifiers:

        1. Definitions (e.g., 'wind speed', 'susceptible individuals')

        2. Units (e.g., 'millimeters', 'per capita')

        3. Constraints (e.g., '> 0', '<= 100')
      required:
        - source
        - types
        - value
      properties:
        source:
          type: string
        type:
          type: string
          enum:
            - definition
            - units
            - constraint
        value:
          type: string

    variable_name:
      title: <variable_name>
      description: >
        `"<namespace_path_string>::<scope_path_string>::<base_name>::<index>"`
      type: string

    function_name:
      title: <function_name>
      description: >
        `"<namespace_path_string>::<scope_path_string>::<base_name>"`
        where:
        `<base_name> ::= <function_type>[$[<var_affected>|<code_given_name>]]`
      type: string

    type_name:
      title: <type_name>
      description: >
        Denotes a non-primitive type; will have a corresponding unique
        `<type_spec>`:
        `"<namespace_path_string>::<scope_path_string>::<base_name>::TYPE"`
      type: string

    type_spec:
      title: <type_spec>
      description: >
        Non-primitive type.
      required:
        - name
        - type
      properties:
        name:
          $ref: '#/components/schemas/type_name'
        type:
          type: string
          enum:
            - "type"
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/attribute_spec'

    attribute_spec:
      title: <attribute_spec>
      description: >
        An attribute of a `<type>`.
      required:
        - name
      properties:
        name:
          type: string
        type:
          $ref: '#/components/schemas/type'

    variable_spec:
      title: <variable_spec>
      description: >
        The specification of a variable hosting a value.
      required:
        - name
        - index
        - domain
        - mutable
      properties:
        name:
          $ref: '#/components/schemas/variable_name'
        index:
          type: integer
        domain:
           $ref: '#/components/schemas/type'
        domain_constraints:
          type: string
          description: >
            String representing a disjunctive normal form representation
            with v = variable value, for example:
            `"(or (and (< v infty) (>= v 5)) (and (> v -infty) (< v 0)))"`
        mutable:
          type: string
          enum:
            - true
            - false
          default: true

    function_assign_spec:
      title: <function_assign_spec>
      description: >
        Setting the value of a variable.
      required:
        - name
        - type
        - arguments
        - return_value
      properties:
        type:
          type: string
          enum:
            - assign
            - condition
            - decision
        lambda_source:
          $ref: '#/components/schemas/lambda_function_source_reference'
        arguments:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/variable_name'
              - $ref: '#/components/schemas/function_name'
        return_value:
          $ref: '#/components/schemas/variable_name'

    function_container_spec:
      title: <function_container_spec>
      description: >
        Representing a function subnetwork.
        Flow through the function body depends on value
        of container "type":
        "container" = flow through once.
        "loop" = repeat flow through.
      required:
        - name
        - type
        - arguments
        - updated
        - return_value
        - body
      properties:
        name:
          $ref: '#/components/schemas/function_name'
        type:
          type: string
          enum:
            - container
            - loop
        arguments:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/variable_name'
              - $ref: '#/components/schemas/function_name'
        updated:
          type: array
          items:
            $ref: '#/components/schemas/variable_name'
        return_value:
          $ref: '#/components/schemas/variable_name'
        body:
          type: array
          items:
            $ref: '#/components/schemas/function_wiring_spec'

    function_wiring_spec:
      title: <function_wiring_spec>
      description: >
        Defines the "wiring" of container functions,
        specifying associations of variables to function
        arguments ("input") and the function return_value ("output").
      required:
        - function
        - input
        - output
      properties:
        function:
          $ref: '#/components/schemas/function_reference'
        input:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/variable_name'
              - $ref: '#/components/schemas/function_name'
        output:
          $ref: '#/components/schemas/variable_name'

    function_reference:
      title: <function_reference>
      description:
        A `<function_reference>` is either a

        1. `<function_name>` denoting a function specification (generally
        an another container function).

        2. `<lambda_function_source_reference>` denoting an executable
        lambda function.


        "type" is a convenience indicating whether the "function" is a
        `<function_name>` or `<lambda_function_source_reference>` without
        having to parse the string.
      required:
        - function
        - type
      properties:
        function:
          oneOf:
            - $ref: '#/components/schemas/function_name'
            - $ref: '#/components/schemas/lambda_function_source_reference'
        type:
          type: string
          enum:
            - function_name
            - lambda_source

    lambda_function_source_reference:
      title: <lambda_function_source_reference>
      description:
        String representation of a path/reference to a function
        in `lambda.py`.
      type: string

    source_code_reference:
      title: <source_code_reference>
      description: >
        String representation of the location within the source
        code where an identifier was used.
      type: string

    source_code_file_path:
      title: <source_code_file_path>
      description: >
        String representation of the path to source file, using
        system root as the path root, and including the file
        extension.
      type: string

    type:
      title: <type>
      description: Root type.
      oneOf:
        - $ref: '#/components/schemas/type_type_spec'
        - $ref: '#/components/schemas/type_integer'
        - $ref: '#/components/schemas/type_float'
        - $ref: '#/components/schemas/type_boolean'
        - $ref: '#/components/schemas/type_string'
        - $ref: '#/components/schemas/type_array'
        - $ref: '#/components/schemas/type_list'
        - $ref: '#/components/schemas/type_map'
        - $ref: '#/components/schemas/type_tuple'

    type_type_spec:
      title: <type_type_spec>
      description: >
        Indicator of a user-defined type_spec.
        "name" is a `<type_name>` that identifies the `<type_spec>`.
      required:
        - name
        - type
      properties:
        name:
          $ref: '#/components/schemas/type_name'
        type:
          type: string
          enum:
            - "type"

    type_integer:
      title: <type_integer>
      description: >
        Primitive scalar integer
      required:
        - name
        - type
      properties:
        name:
          type: string
          enum:
            - "integer"
        type:
          type: string
          enum:
            - "type"

    type_float:
      title: <type_float>
      description: >
        Primitive scalar float
      required:
        - name
        - type
      properties:
        name:
          type: string
          enum:
            - "float"
        type:
          type: string
          enum:
            - "type"

    type_boolean:
      title: <type_boolean>
      description: >
        Primitive scalar boolean
      required:
        - name
        - type
      properties:
        name:
          type: string
          enum:
            - "boolean"
        type:
          type: string
          enum:
            - "type"

    type_string:
      title: <type_string>
      description: >
        Primitive scalar string
      required:
        - name
        - type
      properties:
        name:
          type: string
          enum:
            - "string"
        type:
          type: string
          enum:
            - "type"

    type_array:
      title: <type_array>
      description: >
        Array primitive type.
        Dimension integers can only be positive.
        The "element_type" specifies the `<type>` of the
        elements in the array.
      required:
        - name
        - type
        - dimensions
        - element_type
      properties:
        name:
          type: string
          enum:
            - "array"
        type:
          type: string
          enum:
            - "type"
        dimensions:
          type: array
          items:
            type: integer
        element_type:
           $ref: '#/components/schemas/type'

    type_list:
      title: <type_list>
      description: >
        List primitive type.
      required:
        - name
        - type
      properties:
        name:
          type: string
          enum:
            - "list"
        type:
          type: string
          enum:
            - "type"

    type_map:
      title: <type_map>
      description: >
        Map primitive type.
      required:
        - name
        - type
      properties:
        name:
          type: string
          enum:
            - "map"
        type:
          type: string
          enum:
            - "type"

    type_tuple:
      title: <type_tuple>
      description: >
        Tuple primitive type.
        "element_types" is an array of the `<types>` of each element of the tuple.
        The order of `<types>` corresponds to the order of elements in the
        tuple.
      required:
        - name
        - type
        - element_types
      properties:
        name:
          type: string
          enum:
            - "tuple"
        type:
          type: string
          enum:
            - "type"
        element_types:
          type: array
          items:
            $ref: '#/components/schemas/type'

externalDocs:
  description: Find more information here
  url: 'https://ml4ai.github.io/delphi/grfn_spec.html'
