#!/bin/bash

# Author: Joseph Astier
#
# Test the 'create-model' method of the delphi_rest_api CauseMos 3.0.0 API
#
# input: JSON model definition file with an "id" field
#
# output: A dump of the model JSON file returned by the REST API server
#
# EXAMPLE:
# curl -u me:ivilab4fun -X POST http://localhost:8123/delphi/create-model -d @causemos_create-model.json

inputFile=$1

# make sure user entered a filename
if [[ $inputFile == "" ]]; then

    echo "Please specify a filename."
    echo "Usage: $0 filename"
    exit 1
fi

login="-u me:ivilab4fun"
url=$(./get_delphi_url)
endpoint="/create-model"

call="curl -s $login -X POST $url$endpoint -d @$inputFile"
echo "Call:"
echo $call

call_time=$(date +%T.%3N)
response=$($call)
response_time=$(date +%T.%3N)

echo "Response:"
echo $response | jq
echo "Server queried: $call_time"
echo "Server replied: $response_time"
