#!/bin/bash

# Author: Joseph Astier

# Query a model status from the delphi REST API using the CauseMos 3.0.0 API

modelId=$1

if [[ $modelId == "" ]]; then

        echo "please specify a Model ID"
	echo "Usage:  $0 model_ID"

else
	login="-u me:ivilab4fun"
	endpoint="/models/$modelId"
	url=$(./get_delphi_url)

	call="curl $login -s $url$endpoint"
        echo "Call:"
        echo $call

        response=$($call)
        echo "Response:"
        echo $response | jq
fi

