#!/bin/bash

# Author: Joseph Astier

# Query a model status using CauseMos OpenAPI 3.0.0
#

modelId=$1

if [[ $modelId == "" ]]; then

        echo "please specify a Model ID"
	echo "Usage:  $0 model_ID"

else
	login="-u me:ivilab4fun"
	endpoint="/models/$modelId/training-progress"
	url=$(./get_delphi_url)

	call="curl $login -s $url$endpoint"
	result=$($call)

        echo $result | 'jq' -r '.status'
fi
