#!/bin/bash

# Author: Joseph Astier
#
# CauseMos 3.0.0 API endpoint: "/models/$modelId/training-progress"
#
# Retrieve a model status from the database with the model ID
#
# EXAMPLE:
# curl -s -u me:ivilab4fun http://localhost:8123/models/3nodes/training-progress

modelId=$1

verbose=0

if [[ $modelId == "" ]]; then

    echo "please specify a modelId"
    echo "Usage:  $0 modelId"

else

    login="-u me:ivilab4fun"
    endpoint="/models/$modelId/training-progress"
    url=$(./get_delphi_url)

    call_time=$(date +%T.%3N)
    call="curl -s $login $url$endpoint"

    response=$($call)
    response_time=$(date +%T.%3N)

fi

if [[ $verbose == 1 ]]; then
    echo "Call:"
    echo $call
    echo "Response:"
    echo $response | jq
    echo "Server queried: $call_time"
    echo "Server replied: $response_time"
else
    echo $response | jq
fi
