#!/bin/bash

# Author: Joseph Astier
#
# CauseMos 3.0.0 API endpoint: "/models/$modelId/training-progress"
#
# Retrieve a model status from the database with the model ID
#
# EXAMPLE:  curl -s -u me:ivilab4fun http://localhost:8123/models/3nodes/training-progress

modelId=$1

if [[ $modelId == "" ]]; then

    echo "please specify a modelId"
    echo "Usage:  $0 modelId"

else
    login="-u me:ivilab4fun"
    endpoint="/models/$modelId/training-progress"
    url=$(./get_delphi_url)

    call="curl -s $login $url$endpoint"

    echo "Call:"
    echo $call

    call_time=$(date +%T.%3N)
    response=$($call)
    response_time=$(date +%T.%3N)

    echo "Response:"
    echo $response | jq
    echo "Server queried: $call_time"
    echo "Server replied: $response_time"
fi
