# This is a basic workflow to help you get started with Actions

name: Deploy website to Github Pages

on:
  push:
    branches: 
      - master

jobs:
  deploy_docs:
    runs-on: [ ubuntu-20.04 ]

    steps:
    - uses: actions/checkout@v2

    - name: Build docs
      run: |
        sudo apt-get update
        sudo apt-get install -y\
            libboost-all-dev\
            pkg-config\
            cmake\
            curl\
            tar\
            wget\
            python3-dev\
            python3-venv\
            graphviz\
            librange-v3-dev\
            libeigen3-dev\
            nlohmann-json3-dev\
            pybind11-dev\
            libfmt-dev\
            libgraphviz-dev\
            doxygen

        # install Served (this must come before any 'pip' calls)
        curl -LO https://github.com/meltwater/served/archive/refs/tags/v1.6.0.tar.gz
        tar -xzf v1.6.0.tar.gz
        pushd served-1.6.0
          mkdir build
          cd build
          cmake ..
          sudo make -j `nproc` install
        popd

        python3 -m venv delphi_venv
        source delphi_venv/bin/activate
        pip install wheel
        pip install -e .[docs]
        pushd docs > /dev/null
          make apidocs
          make html
        popd > /dev/null


    - name: Deploy docs to ml4ai.github.io/delphi
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs/_build/html
